### PR TITLE
feat(common): support fixed int enum

### LINKED ISSUE #2591: Generate models with "fixed enum" of int properties from Cadl
Design TBD.

https://github.com/Azure/autorest.csharp/issues/2477 tracks the work to generate fixed enums of strings.

Related design question: https://github.com/Azure/azure-sdk-for-net/pull/30176/files#r932531328

### PR DESCRIPTION
**Pull request by archerzz**
- change `Value` property of `InputenumTypeValue` from `string` to `object`
- add new enum value typs: `InputEnumTypeStringValue`, `InputEnumTypeIntegerValue` and `InputEnumTypeFloatValue`
- change `CadlInputEnumTypeValueConverter` support parsing integer and float types of enum values
- change `CadlInputEnumTypeConverter` to specify more specific enum value types after initial parsing
- change serialization code for int enum, use `WriteNumberValue`
- add test case

resolve #2591

# Description
<i>Add your description here!</i>

# Checklist

To ensure a quick review and merge, please ensure:
- [ ] The PR has a understandable title and description explaining the _why_ and _what_.
- [ ] The PR is opened in draft if not ready for review yet.
   - If opened in draft, please allocate sufficient time (24 hours) after moving out of draft for review
- [ ] The branch is recent enough to not have merge conflicts upon creation.

# Ready to Land?
- [ ] Build is completely green
   - Submissions with test failures require tracking issue and approval of a CODEOWNER
- [ ] At least one +1 review by a CODEOWNER
- [ ] All -1 reviews are confirmed resolved by the reviewer 
   - Override/Marking reviews stale must be discussed with CODEOWNERS first

### CODE REVIEW

File: test/TestProjects/Models-Cadl/Generated/FixedIntEnum.Serialization.cs [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+
+// <auto-generated/>
+
+#nullable disable
+
+using System;
+
+namespace ModelsInCadl
+{
+    internal static partial class FixedIntEnumExtensions
```
Comment (archerzz) [inline test/TestProjects/Models-Cadl/Generated/FixedIntEnum.Serialization.cs:12]: One thing we could optimize is to delete the serialization class for fixed int enum, since it's int value by nature in .net. However, doing so will result in changes across various places in the generator. Some changes are non-trivial.

File: test/TestProjects/Models-Cadl/Generated/FixedIntEnum.Serialization.cs [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+    {
+        public static int ToSerialString(this FixedIntEnum value) => value switch
```
Comment (archerzz) [inline test/TestProjects/Models-Cadl/Generated/FixedIntEnum.Serialization.cs:14]: Another thing to improve is the name of the serialization method. It's called `ToSerialString` which cannot cover other types we plan to support. Better to rename it to `ToSerializationValue`

File: test/TestProjects/Models-Cadl/Generated/FixedIntEnum.cs [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+
+#nullable disable
+
+namespace ModelsInCadl
+{
+    /// <summary> Fixed int enum. </summary>
+    public enum FixedIntEnum
+    {
+        /// <summary> 1. </summary>
+        One,
```
Comment (archerzz) [inline test/TestProjects/Models-Cadl/Generated/FixedIntEnum.cs:14]: If we still keep serialization class, one thing we could improve for int value is that we could set the value for enum value, like `One = 1,`.

File: src/AutoRest.CSharp/Common/Input/Inputs.cs [hunk 4]
```diff
@@ -192,7 +192,15 @@ internal record InputModelProperty(string Name, string? SerializedName, string D
...
-    internal record InputEnumTypeValue(string Name, string Value, string? Description);
+    internal record InputEnumTypeValue(string Name, object Value, string? Description)
+    {
+        public virtual string GetJsonValueString() => GetValueString();
+        public string GetValueString() => (Value.ToString() ?? string.Empty);
+    }
+
+    internal record InputEnumTypeStringValue(string Name, string StringValue, string? Description) : InputEnumTypeValue(Name, StringValue, Description);
+    internal record InputEnumTypeIntegerValue(string Name, Int32 IntegerValue, string? Description) : InputEnumTypeValue(Name, IntegerValue, Description);
+    internal record InputEnumTypeFloatValue(string Name, float FloatValue, string? Description) : InputEnumTypeValue(Name, FloatValue, Description);
```
[the remark this answers is not in the document]
Comment (archerzz) [reply src/AutoRest.CSharp/Common/Input/Inputs.cs:203]: > Why do we generate float enum? in C#, the enum value is integer, and it only can wrap float as constant as we did for string type. And I don't see cadl support to define float enum.

No. Right now in emitter we only support int enum. Cadl does support float enum: https://microsoft.github.io/cadl/docs/language-basics/enums/#values
I think our support for float enum is the same as string, e.g. we will serialize and de-serialize in the generated serialization class.

**Comment by archerzz** [comment]
This is a conservative solution to implement fixed int enum support. A few key points:
- It still generates serialization class. For int enum, we actually do not need serialization class because in .Net enum is int value. I keep it because if we remove serialization class, there will be many changes in existing generator codes.
- The parsing of incoming enum definition is a two-pass process.
  - In the first iteration, we parse the JSON enum definitions into `InputEnumTypeValue` which is a base class with `object Value` property.
  - In the second iteration, we will check the `ValueType` property of `InputEnumType` and then use that information to convert to more specific enum type values (e.g. `InputEnumTypeStringValue`, `InputEnumTypeIntegerValue` and `InputEnumTypeFloatValue`).
  - The process is not ideal, because I could not find a more elegant way to parse the enum value in one-pass.
    - We should not assume the sequence of properties of `InputEnumType`, so when parsing he `ValueType` and `AllowedValues` we could not assume the their sequence, thus we could not specify the exact value type when parsing `AllowedValues`.
    - I tried to get the raw bytes of `AllowedValues`, so that we could parse them after we parsed the `InputEnumType`. But I could not find a way to get the raw bytes. The stream API of `System.Text.Json` doesn't provide a way to fetch them.

**Comment by archerzz** [comment]
## Performance Comparison

I run the following benchmark codes.
```csharp
    [SimpleJob(RuntimeMoniker.Net461)]
    [SimpleJob(RuntimeMoniker.Net60)]
    [SimpleJob(RuntimeMoniker.NetCoreApp31)]
    public class IntEnumSerliazationBenchmark
    {
        [Params(1, 2, 4)]
        public int Value;

        [Benchmark]
        public FixedIntEnum UseDeserializationMethod()
        {
            return Value.ToFixedIntEnum();
        }

        [Benchmark]
        public FixedIntEnum UseSystemIntrinsicMethod()
        {
            if (Enum.IsDefined(typeof(FixedIntEnum), Value))
            {
                return (FixedIntEnum)Enum.ToObject(typeof(FixedIntEnum), Value);
            }
            else
            {
                throw new ArgumentOutOfRangeException(nameof(Value), Value, "Unknown FixedIntEnum value.");
            }
        }
    }
``

And the result is as follows.
```
|                   Method |                  Job |              Runtime | Value |       Mean |     Error |    StdDev |
|------------------------- |--------------------- |--------------------- |------ |-----------:|----------:|----------:|
| UseDeserializationMethod |             .NET 6.0 |             .NET 6.0 |     1 |   7.205 ns | 0.0479 ns | 0.0400 ns |
| UseSystemIntrinsicMethod |             .NET 6.0 |             .NET 6.0 |     1 | 164.200 ns | 0.5609 ns | 0.4683 ns |
| UseDeserializationMethod |        .NET Core 3.1 |        .NET Core 3.1 |     1 |  11.630 ns | 0.0524 ns | 0.0490 ns |
| UseSystemIntrinsicMethod |        .NET Core 3.1 |        .NET Core 3.1 |     1 | 170.961 ns | 1.1150 ns | 0.9884 ns |
| UseDeserializationMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |     1 |   9.875 ns | 0.0994 ns | 0.0881 ns |
| UseSystemIntrinsicMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |     1 | 194.658 ns | 1.4495 ns | 1.3559 ns |
| UseDeserializationMethod |             .NET 6.0 |             .NET 6.0 |     2 |  14.817 ns | 0.2768 ns | 0.2454 ns |
| UseSystemIntrinsicMethod |             .NET 6.0 |             .NET 6.0 |     2 | 159.392 ns | 1.2592 ns | 1.1778 ns |
| UseDeserializationMethod |        .NET Core 3.1 |        .NET Core 3.1 |     2 |  23.051 ns | 0.1183 ns | 0.1107 ns |
| UseSystemIntrinsicMethod |        .NET Core 3.1 |        .NET Core 3.1 |     2 | 169.208 ns | 1.0923 ns | 0.8528 ns |
| UseDeserializationMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |     2 |  19.965 ns | 0.3222 ns | 0.3014 ns |
| UseSystemIntrinsicMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |     2 | 195.447 ns | 1.3809 ns | 1.1531 ns |
| UseDeserializationMethod |             .NET 6.0 |             .NET 6.0 |     4 |  22.447 ns | 0.1357 ns | 0.1203 ns |
| UseSystemIntrinsicMethod |             .NET 6.0 |             .NET 6.0 |     4 | 159.490 ns | 0.5889 ns | 0.5220 ns |
| UseDeserializationMethod |        .NET Core 3.1 |        .NET Core 3.1 |     4 |  35.416 ns | 0.1923 ns | 0.1799 ns |
| UseSystemIntrinsicMethod |        .NET Core 3.1 |        .NET Core 3.1 |     4 | 174.281 ns | 1.2075 ns | 1.0704 ns |
| UseDeserializationMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |     4 |  29.862 ns | 0.1925 ns | 0.1503 ns |
| UseSystemIntrinsicMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |     4 | 200.741 ns | 1.3288 ns | 1.2429 ns |
```

Deserialization method in the serialization class is way faster than system intrinsic methods.

File: test/TestProjects/Models-Cadl/Generated/FixedIntEnum.Serialization.cs (hunk 2 above)
Comment (archerzz) [reply test/TestProjects/Models-Cadl/Generated/FixedIntEnum.Serialization.cs]: I changed the method name to `ToSerial{Type}`, so that for existing enum types the method name is not changed.

File: test/TestProjects/Models-Cadl/Generated/FixedIntEnum.cs (hunk 3 above)
Comment (archerzz) [reply test/TestProjects/Models-Cadl/Generated/FixedIntEnum.cs]: Added int value assignment, so that the enum values are consistent with the definition.

**Comment by archerzz** [comment]
list of changes:
- add assignment of int value to enum values, like `One = 1,`
- name the serialization method after `ToSerial{Type}`
  - for existing enum types, the serialization method name won't change
- add test case for mgmt plane

**Comment by archerzz** [comment]
## Performance Benchmark for int enum serialization

I used the following benchmark codes to compare the serialization performance of int enum, e.g. existing serialization method v.s. type case.

```csharp
    [SimpleJob(RuntimeMoniker.Net461)]
    [SimpleJob(RuntimeMoniker.Net60)]
    [SimpleJob(RuntimeMoniker.NetCoreApp31)]
    public class IntEnumSerliazationBenchmark
    {
        [Params(FixedIntEnum.One, FixedIntEnum.Two, FixedIntEnum.Four)]
        public FixedIntEnum Value;

        [Benchmark]
        public int UseSerializationMethod()
        {
            return Value.ToSerialInt32();
        }

        [Benchmark]
        public int UseTypeCast()
        {
            return (int)Value;
        }
    }
```

### Result

Apparently type case is much faster.

|                 Method |                  Job |              Runtime | Value |      Mean |     Error |    StdDev |    Median |
|----------------------- |--------------------- |--------------------- |------ |----------:|----------:|----------:|----------:|
| UseSerializationMethod |             .NET 6.0 |             .NET 6.0 |   One | 1.8520 ns | 0.0100 ns | 0.0083 ns | 1.8503 ns |
|            UseTypeCast |             .NET 6.0 |             .NET 6.0 |   One | 0.0007 ns | 0.0031 ns | 0.0026 ns | 0.0000 ns |
| UseSerializationMethod |        .NET Core 3.1 |        .NET Core 3.1 |   One | 2.0750 ns | 0.0171 ns | 0.0160 ns | 2.0716 ns |
|            UseTypeCast |        .NET Core 3.1 |        .NET Core 3.1 |   One | 0.0001 ns | 0.0006 ns | 0.0005 ns | 0.0000 ns |
| UseSerializationMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |   One | 1.9111 ns | 0.0309 ns | 0.0274 ns | 1.9106 ns |
|            UseTypeCast | .NET Framework 4.6.1 | .NET Framework 4.6.1 |   One | 0.0054 ns | 0.0045 ns | 0.0042 ns | 0.0052 ns |
| UseSerializationMethod |             .NET 6.0 |             .NET 6.0 |   Two | 1.8130 ns | 0.0155 ns | 0.0145 ns | 1.8148 ns |
|            UseTypeCast |             .NET 6.0 |             .NET 6.0 |   Two | 0.0009 ns | 0.0030 ns | 0.0025 ns | 0.0000 ns |
| UseSerializationMethod |        .NET Core 3.1 |        .NET Core 3.1 |   Two | 2.0381 ns | 0.0402 ns | 0.0356 ns | 2.0267 ns |
|            UseTypeCast |        .NET Core 3.1 |        .NET Core 3.1 |   Two | 0.0061 ns | 0.0054 ns | 0.0048 ns | 0.0055 ns |
| UseSerializationMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |   Two | 1.9173 ns | 0.0370 ns | 0.0328 ns | 1.9283 ns |
|            UseTypeCast | .NET Framework 4.6.1 | .NET Framework 4.6.1 |   Two | 0.0031 ns | 0.0038 ns | 0.0032 ns | 0.0017 ns |
| UseSerializationMethod |             .NET 6.0 |             .NET 6.0 |  Four | 1.6063 ns | 0.0110 ns | 0.0103 ns | 1.6050 ns |
|            UseTypeCast |             .NET 6.0 |             .NET 6.0 |  Four | 0.0000 ns | 0.0002 ns | 0.0001 ns | 0.0000 ns |
| UseSerializationMethod |        .NET Core 3.1 |        .NET Core 3.1 |  Four | 1.8376 ns | 0.0642 ns | 0.0714 ns | 1.8211 ns |
|            UseTypeCast |        .NET Core 3.1 |        .NET Core 3.1 |  Four | 0.0000 ns | 0.0001 ns | 0.0001 ns | 0.0000 ns |
| UseSerializationMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |  Four | 1.6511 ns | 0.0266 ns | 0.0236 ns | 1.6488 ns |
|            UseTypeCast | .NET Framework 4.6.1 | .NET Framework 4.6.1 |  Four | 0.0097 ns | 0.0083 ns | 0.0077 ns | 0.0072 ns |

I even got a warning that type cast cost is almost zero.

```
// * Warnings *
ZeroMeasurement
  IntEnumSerliazationBenchmark.UseTypeCast: .NET 6.0             -> The method duration is indistinguishable from the empty method duration
  IntEnumSerliazationBenchmark.UseTypeCast: .NET Core 3.1        -> The method duration is indistinguishable from the empty method duration
```

## Conclusion

I think we should delete serialization method for int enum, and using type cast when serializing int enum.

**Comment by archerzz** [comment]
## Benchmark for string enum desrialization

I've changed the string enum serialization class as follows:
```csharp
    internal static partial class FixedStringEnumExtensions
    {
        private const string One = "1";
        private const string Two = "2";
        private const string Four = "4";

        public static string ToSerialString(this FixedStringEnum value) => value switch
        {
            FixedStringEnum.One => "1",
            FixedStringEnum.Two => "2",
            FixedStringEnum.Four => "4",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown FixedStringEnum value.")
        };

        public static FixedStringEnum ToFixedStringEnum(this string value)
        {
            if (string.Equals(value, "1", StringComparison.InvariantCultureIgnoreCase)) return FixedStringEnum.One;
            if (string.Equals(value, "2", StringComparison.InvariantCultureIgnoreCase)) return FixedStringEnum.Two;
            if (string.Equals(value, "4", StringComparison.InvariantCultureIgnoreCase)) return FixedStringEnum.Four;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown FixedStringEnum value.");
        }

        public static FixedStringEnum ToFixedStringEnum(this JsonElement value)
        {
            if (value.ValueEquals("1"))
                return FixedStringEnum.One;
            if (value.ValueEquals("2"))
                return FixedStringEnum.Two;
            if (value.ValueEquals("4"))
                return FixedStringEnum.Four;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown FixedStringEnum value.");
        }

        public static FixedStringEnum ToFixedStringEnumWithConst(this JsonElement value)
        {
            if (value.ValueEquals(One))
                return FixedStringEnum.One;
            if (value.ValueEquals(Two))
                return FixedStringEnum.Two;
            if (value.ValueEquals(Four))
                return FixedStringEnum.Four;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown FixedStringEnum value.");
        }
    }
```

The benchmark codes are as follows:
```csharp
    [SimpleJob(RuntimeMoniker.Net461)]
    [SimpleJob(RuntimeMoniker.Net60)]
    [SimpleJob(RuntimeMoniker.NetCoreApp31)]
    public class StringEnumDeserliazationBenchmark
    {
        [ParamsSource(nameof(JsonValues))]
        public JsonElement JsonValue;

        public static IEnumerable<JsonElement> JsonValues()
        {
            foreach (var value in new string[] { "\"1\"", "\"2\"", "\"4\""})
            {
                yield return JsonDocument.Parse(value).RootElement;
            }

        }

        [Benchmark]
        public FixedStringEnum UseDeserializationMethod()
        {
            return JsonValue.GetString().ToFixedStringEnum();
        }

        [Benchmark]
        public FixedStringEnum UseJsonElementMethod()
        {
            return JsonValue.ToFixedStringEnum();
        }

        [Benchmark]
        public FixedStringEnum UseJsonElementConstMethod()
        {
            return JsonValue.ToFixedStringEnumWithConst();
        }
    }
```

### Result

|                    Method |                  Job |              Runtime | JsonValue |      Mean |    Error |   StdDev |    Median |
|-------------------------- |--------------------- |--------------------- |---------- |----------:|---------:|---------:|----------:|
|  UseDeserializationMethod |             .NET 6.0 |             .NET 6.0 |         1 |  33.16 ns | 0.280 ns | 0.234 ns |  33.09 ns |
|      UseJsonElementMethod |             .NET 6.0 |             .NET 6.0 |         1 |  27.32 ns | 0.160 ns | 0.134 ns |  27.36 ns |
| UseJsonElementConstMethod |             .NET 6.0 |             .NET 6.0 |         1 |  27.12 ns | 0.157 ns | 0.139 ns |  27.10 ns |
|  UseDeserializationMethod |        .NET Core 3.1 |        .NET Core 3.1 |         1 |  53.20 ns | 0.558 ns | 0.522 ns |  53.13 ns |
|      UseJsonElementMethod |        .NET Core 3.1 |        .NET Core 3.1 |         1 |  37.64 ns | 0.231 ns | 0.205 ns |  37.63 ns |
| UseJsonElementConstMethod |        .NET Core 3.1 |        .NET Core 3.1 |         1 |  37.19 ns | 0.331 ns | 0.276 ns |  37.20 ns |
|  UseDeserializationMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |         1 |  77.83 ns | 0.731 ns | 0.648 ns |  77.86 ns |
|      UseJsonElementMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |         1 | 101.07 ns | 0.700 ns | 0.620 ns | 100.85 ns |
| UseJsonElementConstMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |         1 |  99.96 ns | 0.693 ns | 0.649 ns |  99.72 ns |
|  UseDeserializationMethod |             .NET 6.0 |             .NET 6.0 |         2 |  70.82 ns | 0.645 ns | 0.634 ns |  70.65 ns |
|      UseJsonElementMethod |             .NET 6.0 |             .NET 6.0 |         2 |  56.89 ns | 0.498 ns | 0.416 ns |  56.67 ns |
| UseJsonElementConstMethod |             .NET 6.0 |             .NET 6.0 |         2 |  51.93 ns | 0.616 ns | 0.515 ns |  51.85 ns |
|  UseDeserializationMethod |        .NET Core 3.1 |        .NET Core 3.1 |         2 |  97.57 ns | 0.636 ns | 0.496 ns |  97.61 ns |
|      UseJsonElementMethod |        .NET Core 3.1 |        .NET Core 3.1 |         2 |  71.31 ns | 0.790 ns | 0.739 ns |  70.96 ns |
| UseJsonElementConstMethod |        .NET Core 3.1 |        .NET Core 3.1 |         2 |  73.84 ns | 1.496 ns | 3.807 ns |  71.97 ns |
|  UseDeserializationMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |         2 | 153.37 ns | 2.917 ns | 7.372 ns | 150.03 ns |
|      UseJsonElementMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |         2 | 201.13 ns | 4.046 ns | 7.986 ns | 197.16 ns |
| UseJsonElementConstMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |         2 | 195.09 ns | 1.969 ns | 1.746 ns | 194.60 ns |
|  UseDeserializationMethod |             .NET 6.0 |             .NET 6.0 |         4 | 107.37 ns | 0.355 ns | 0.277 ns | 107.42 ns |
|      UseJsonElementMethod |             .NET 6.0 |             .NET 6.0 |         4 |  80.12 ns | 1.382 ns | 1.225 ns |  80.07 ns |
| UseJsonElementConstMethod |             .NET 6.0 |             .NET 6.0 |         4 |  79.11 ns | 0.732 ns | 0.649 ns |  78.99 ns |
|  UseDeserializationMethod |        .NET Core 3.1 |        .NET Core 3.1 |         4 | 146.61 ns | 1.283 ns | 1.138 ns | 146.29 ns |
|      UseJsonElementMethod |        .NET Core 3.1 |        .NET Core 3.1 |         4 | 107.91 ns | 0.575 ns | 0.449 ns | 107.75 ns |
| UseJsonElementConstMethod |        .NET Core 3.1 |        .NET Core 3.1 |         4 | 107.68 ns | 1.043 ns | 0.871 ns | 107.69 ns |
|  UseDeserializationMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |         4 | 210.75 ns | 1.198 ns | 0.935 ns | 210.84 ns |
|      UseJsonElementMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |         4 | 289.61 ns | 2.373 ns | 2.219 ns | 289.22 ns |
| UseJsonElementConstMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |         4 | 287.90 ns | 1.175 ns | 1.042 ns | 287.70 ns |

## Conclusion

- Using `JsonElement.ValueEquals()` is faster except for .Net 4.6.1 on which the performance regression is non-trivial.
- There is almost no difference between `JsonElement.ValueEquals("1")` and `JsonElement.ValueEquals(One)`, except for .Net 4.6.1. Even on .Net 4.6.1, the difference is very small.

**Comment by archerzz** [comment]
## Benchmark for optimized string deserialization

I changed the deserialization codes in:

- Use `StringComparison.OrdinalIgnoreCase` for string comparision
- Use `String.AsSpan()` for `JsonElement.ValueEquals()`

The updated codes are as follows:

```csharp
    internal static partial class FixedStringEnumExtensions
    {
        private const string One = "1";
        private const string Two = "2";
        private const string Four = "4";

        public static string ToSerialString(this FixedStringEnum value) => value switch
        {
            FixedStringEnum.One => "1",
            FixedStringEnum.Two => "2",
            FixedStringEnum.Four => "4",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown FixedStringEnum value.")
        };

        public static FixedStringEnum ToFixedStringEnum(this string value)
        {
            if (string.Equals(value, "1", StringComparison.OrdinalIgnoreCase)) return FixedStringEnum.One;
            if (string.Equals(value, "2", StringComparison.OrdinalIgnoreCase)) return FixedStringEnum.Two;
            if (string.Equals(value, "4", StringComparison.OrdinalIgnoreCase)) return FixedStringEnum.Four;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown FixedStringEnum value.");
        }

        public static FixedStringEnum ToFixedStringEnum(this JsonElement value)
        {
            if (value.ValueEquals("1".AsSpan()))
                return FixedStringEnum.One;
            if (value.ValueEquals("2".AsSpan()))
                return FixedStringEnum.Two;
            if (value.ValueEquals("4".AsSpan()))
                return FixedStringEnum.Four;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown FixedStringEnum value.");
        }

        public static FixedStringEnum ToFixedStringEnumWithConst(this JsonElement value)
        {
            if (value.ValueEquals(One.AsSpan()))
                return FixedStringEnum.One;
            if (value.ValueEquals(Two.AsSpan()))
                return FixedStringEnum.Two;
            if (value.ValueEquals(Four.AsSpan()))
                return FixedStringEnum.Four;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown FixedStringEnum value.");
        }
    }
```


### Performance

TL;DR

- String comparison is much faster, and it's even faster than `JsonElement.ValueEquals()`
- There is little difference between new/old versions 

| Method                    | Job                  | Runtime              | JsonValue | Before    | After     | Difference | Percentage |
|---------------------------|----------------------|----------------------|-----------|-----------|-----------|------------|------------|
| UseDeserializationMethod  | .NET 6.0             | .NET 6.0             | 1         | 33.16 ns  | 11.28 ns  | -21.9      | -66.16%    |
| UseJsonElementMethod      | .NET 6.0             | .NET 6.0             | 1         | 27.32 ns  | 28.22 ns  | 0.9        | 3.30%      |
| UseJsonElementConstMethod | .NET 6.0             | .NET 6.0             | 1         | 27.12 ns  | 27.79 ns  | 0.6        | 2.21%      |
| UseDeserializationMethod  | .NET Core 3.1        | .NET Core 3.1        | 1         | 53.20 ns  | 10.84 ns  | -42.4      | -79.70%    |
| UseJsonElementMethod      | .NET Core 3.1        | .NET Core 3.1        | 1         | 37.64 ns  | 37.12 ns  | -0.5       | -1.33%     |
| UseJsonElementConstMethod | .NET Core 3.1        | .NET Core 3.1        | 1         | 37.19 ns  | 38.16 ns  | 1          | 2.70%      |
| UseDeserializationMethod  | .NET Framework 4.6.1 | .NET Framework 4.6.1 | 1         | 77.83 ns  | 21.37 ns  | -56.5      | -72.62%    |
| UseJsonElementMethod      | .NET Framework 4.6.1 | .NET Framework 4.6.1 | 1         | 101.07 ns | 109.74 ns | 8.7        | 8.61%      |
| UseJsonElementConstMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 | 1         | 99.96 ns  | 110.05 ns | 10.1       | 10.11%     |
| UseDeserializationMethod  | .NET 6.0             | .NET 6.0             | 2         | 70.82 ns  | 16.59 ns  | -54.3      | -76.69%    |
| UseJsonElementMethod      | .NET 6.0             | .NET 6.0             | 2         | 56.89 ns  | 52.38 ns  | -4.5       | -7.92%     |
| UseJsonElementConstMethod | .NET 6.0             | .NET 6.0             | 2         | 51.93 ns  | 52.07 ns  | 0.1        | 0.19%      |
| UseDeserializationMethod  | .NET Core 3.1        | .NET Core 3.1        | 2         | 97.57 ns  | 19.28 ns  | -78.3      | -80.31%    |
| UseJsonElementMethod      | .NET Core 3.1        | .NET Core 3.1        | 2         | 71.31 ns  | 72.60 ns  | 1.3        | 1.82%      |
| UseJsonElementConstMethod | .NET Core 3.1        | .NET Core 3.1        | 2         | 73.84 ns  | 72.78 ns  | -1.1       | -1.49%     |
| UseDeserializationMethod  | .NET Framework 4.6.1 | .NET Framework 4.6.1 | 2         | 153.37 ns | 29.97 ns  | -123.4     | -80.50%    |
| UseJsonElementMethod      | .NET Framework 4.6.1 | .NET Framework 4.6.1 | 2         | 201.13 ns | 209.65 ns | 8.5        | 4.23%      |
| UseJsonElementConstMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 | 2         | 195.09 ns | 209.63 ns | 14.6       | 7.49%      |
| UseDeserializationMethod  | .NET 6.0             | .NET 6.0             | 4         | 107.37 ns | 22.00 ns  | -85.3      | -79.50%    |
| UseJsonElementMethod      | .NET 6.0             | .NET 6.0             | 4         | 80.12 ns  | 78.21 ns  | -1.9       | -2.37%     |
| UseJsonElementConstMethod | .NET 6.0             | .NET 6.0             | 4         | 79.11 ns  | 76.96 ns  | -2.2       | -2.78%     |
| UseDeserializationMethod  | .NET Core 3.1        | .NET Core 3.1        | 4         | 146.61 ns | 25.66 ns  | -121       | -82.54%    |
| UseJsonElementMethod      | .NET Core 3.1        | .NET Core 3.1        | 4         | 107.91 ns | 107.66 ns | -0.3       | -0.28%     |
| UseJsonElementConstMethod | .NET Core 3.1        | .NET Core 3.1        | 4         | 107.68 ns | 105.87 ns | -1.8       | -1.67%     |
| UseDeserializationMethod  | .NET Framework 4.6.1 | .NET Framework 4.6.1 | 4         | 210.75 ns | 37.75 ns  | -173       | -82.11%    |
| UseJsonElementMethod      | .NET Framework 4.6.1 | .NET Framework 4.6.1 | 4         | 289.61 ns | 314.55 ns | 24.9       | 8.60%      |
| UseJsonElementConstMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 | 4         | 287.90 ns | 314.32 ns | 26.4       | 9.17%      |

**Comment by archerzz** [comment]
## Optimize Number Value Comparison

Use `if (value == 1)` instead of `if (Equals(value, 1))`. The reason we don't use `switch(value) { case 1:...}` is that switch statement will create a jump table which is actually inferior in performance, because jump table has negative impact on CPU branch prediction. See the benchmarks below.

## Benchmarks

### Sample Codes

Below are the deserialization methods based on switch-case statement and if-else statement.
```csharp
        public static FixedIntEnum ToFixedIntEnum2(this int value)
        {
            switch (value)
            {
                case 1:
                    return FixedIntEnum.One;
                case 2:
                    return FixedIntEnum.Two;
                case 4:
                    return FixedIntEnum.Four;
                default:
                    throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown FixedIntEnum value.");
            }
        }

        public static FixedIntEnum ToFixedIntEnum3(this int value)
        {
            if (value == 1)
                return FixedIntEnum.One;
            if (value == 2)
                return FixedIntEnum.Two;
            if (value == 4)
                return FixedIntEnum.Four;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown FixedIntEnum value.");
        }
```

### Time

|                    Method |                  Job |              Runtime | Value |       Mean |     Error |    StdDev |     Median |
|-------------------------- |--------------------- |--------------------- |------ |-----------:|----------:|----------:|-----------:|
|  UseDeserializationMethod |             .NET 6.0 |             .NET 6.0 |     1 |  7.7540 ns | 0.1817 ns | 0.1611 ns |  7.7093 ns |
| UseSwitchCase |             .NET 6.0 |             .NET 6.0 |     1 |  1.5215 ns | 0.0258 ns | 0.0215 ns |  1.5140 ns |
| UseIfElseComparison |             .NET 6.0 |             .NET 6.0 |     1 |  0.7930 ns | 0.0244 ns | 0.0229 ns |  0.7887 ns |
|  UseDeserializationMethod |        .NET Core 3.1 |        .NET Core 3.1 |     1 | 11.9211 ns | 0.2493 ns | 0.2082 ns | 11.8504 ns |
| UseSwitchCase |        .NET Core 3.1 |        .NET Core 3.1 |     1 |  1.4082 ns | 0.0208 ns | 0.0184 ns |  1.4054 ns |
| UseIfElseComparison |        .NET Core 3.1 |        .NET Core 3.1 |     1 |  0.8310 ns | 0.0186 ns | 0.0145 ns |  0.8282 ns |
|  UseDeserializationMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |     1 |  9.9337 ns | 0.0554 ns | 0.0519 ns |  9.9249 ns |
| UseSwitchCase | .NET Framework 4.6.1 | .NET Framework 4.6.1 |     1 |  1.3630 ns | 0.0139 ns | 0.0130 ns |  1.3634 ns |
| UseIfElseComparison | .NET Framework 4.6.1 | .NET Framework 4.6.1 |     1 |  0.7816 ns | 0.0160 ns | 0.0149 ns |  0.7730 ns |
|  UseDeserializationMethod |             .NET 6.0 |             .NET 6.0 |     2 | 14.8969 ns | 0.2721 ns | 0.2412 ns | 14.8242 ns |
| UseSwitchCase |             .NET 6.0 |             .NET 6.0 |     2 |  1.5041 ns | 0.0349 ns | 0.0273 ns |  1.5023 ns |
| UseIfElseComparison |             .NET 6.0 |             .NET 6.0 |     2 |  0.8476 ns | 0.0110 ns | 0.0103 ns |  0.8448 ns |
|  UseDeserializationMethod |        .NET Core 3.1 |        .NET Core 3.1 |     2 | 22.5897 ns | 0.1398 ns | 0.1239 ns | 22.5811 ns |
| UseSwitchCase |        .NET Core 3.1 |        .NET Core 3.1 |     2 |  1.6566 ns | 0.0193 ns | 0.0171 ns |  1.6541 ns |
| UseIfElseComparison |        .NET Core 3.1 |        .NET Core 3.1 |     2 |  1.0372 ns | 0.0133 ns | 0.0124 ns |  1.0368 ns |
|  UseDeserializationMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |     2 | 19.8582 ns | 0.2264 ns | 0.1767 ns | 19.8251 ns |
| UseSwitchCase | .NET Framework 4.6.1 | .NET Framework 4.6.1 |     2 |  1.6053 ns | 0.0256 ns | 0.0227 ns |  1.6061 ns |
| UseIfElseComparison | .NET Framework 4.6.1 | .NET Framework 4.6.1 |     2 |  1.0515 ns | 0.0233 ns | 0.0195 ns |  1.0503 ns |
|  UseDeserializationMethod |             .NET 6.0 |             .NET 6.0 |     4 | 21.6930 ns | 0.0944 ns | 0.0789 ns | 21.6769 ns |
| UseSwitchCase |             .NET 6.0 |             .NET 6.0 |     4 |  1.5794 ns | 0.0193 ns | 0.0181 ns |  1.5784 ns |
| UseIfElseComparison |             .NET 6.0 |             .NET 6.0 |     4 |  1.3624 ns | 0.0186 ns | 0.0165 ns |  1.3590 ns |
|  UseDeserializationMethod |        .NET Core 3.1 |        .NET Core 3.1 |     4 | 35.8868 ns | 0.3233 ns | 0.3024 ns | 35.9300 ns |
| UseSwitchCase |        .NET Core 3.1 |        .NET Core 3.1 |     4 |  1.4654 ns | 0.0486 ns | 0.1087 ns |  1.4116 ns |
| UseIfElseComparison |        .NET Core 3.1 |        .NET Core 3.1 |     4 |  1.5487 ns | 0.0149 ns | 0.0139 ns |  1.5478 ns |
|  UseDeserializationMethod | .NET Framework 4.6.1 | .NET Framework 4.6.1 |     4 | 30.5178 ns | 0.6054 ns | 0.6729 ns | 30.4213 ns |
| UseSwitchCase | .NET Framework 4.6.1 | .NET Framework 4.6.1 |     4 |  1.3523 ns | 0.0233 ns | 0.0207 ns |  1.3476 ns |
| UseIfElseComparison | .NET Framework 5.6.1 | .NET Framework 4.6.1 |     4 |  1.3691 ns | 0.0200 ns | 0.0177 ns |  1.3671 ns |

File: src/AutoRest.CSharp/Common/Input/Utf8JsonReaderExtensions.cs [hunk 5]
```diff
@@ -70,6 +70,46 @@ public static bool TryReadString(this ref Utf8JsonReader reader, string property
...
+            if (reader.GetString() != propertyName)
+            {
+                return false;
+            }
+
+            reader.Read();
+            switch (reader.TokenType)
+            {
+                case JsonTokenType.String:
+                    value = reader.GetString() ?? throw new JsonException();
```
Comment (lirenhe) [inline src/AutoRest.CSharp/Common/Input/Utf8JsonReaderExtensions.cs:89]: Better to provide some information in the exception to help trouble shooting.

File: src/AutoRest.CSharp/Common/Generation/Writers/JsonCodeWriterExtensions.cs [hunk 6]
```diff
@@ -203,9 +203,16 @@ public static void ToSerializeCall(this CodeWriter writer, JsonSerialization ser
                             writer.Line($"{writerName}.WriteObjectValue({name:I});");
                             return;
 
+                        case EnumType clientEnum when clientEnum.IsIntValueType & !clientEnum.IsExtensible:
```
Comment (lirenhe) [inline src/AutoRest.CSharp/Common/Generation/Writers/JsonCodeWriterExtensions.cs:206]: what is the best practise here?  use '&&' or '&'

File: src/AutoRest.CSharp/Common/Input/Utf8JsonReaderExtensions.cs [hunk 7]
```diff
@@ -70,6 +70,46 @@ public static bool TryReadString(this ref Utf8JsonReader reader, string property
...
+                    break;
+                case JsonTokenType.Number:
+                    if (reader.TryGetInt32(out int intValue))
+                    {
+                        value = intValue;
+                    }
+                    else if (reader.TryGetSingle(out float floatValue))
```
Comment (lirenhe) [inline src/AutoRest.CSharp/Common/Input/Utf8JsonReaderExtensions.cs:96]: If we don't support float now, shall we raise exception directly?

Comment (archerzz) [reply src/AutoRest.CSharp/Common/Input/Utf8JsonReaderExtensions.cs:96]: CADL actually [supports float](https://microsoft.github.io/cadl/language-basics/enums#values).

I didn't include the full float support in this PR, because:
1. There is an issue in the sample of CADL doc. I've asked for clarification.
2. I want to confirm the way we handle fixed enum in the PR, so that it would be easier to add the float support in a separate PR.

File: src/AutoRest.CSharp/Common/Generation/Writers/JsonCodeWriterExtensions.cs (hunk 6 above)
Comment (archerzz) [reply src/AutoRest.CSharp/Common/Generation/Writers/JsonCodeWriterExtensions.cs:206]: Good catch. It should be `&&`. I'll change to use a more explicit way.

File: src/AutoRest.CSharp/Common/Input/Utf8JsonReaderExtensions.cs (hunk 5 above)
Comment (archerzz) [reply src/AutoRest.CSharp/Common/Input/Utf8JsonReaderExtensions.cs]: done

**Review by lirenhe — APPROVED** [review]
LGTM

File: test/TestProjects/Models-Cadl/Generated/FixedIntEnum.Serialization.cs (hunk 1 above)
Comment (archerzz) [reply test/TestProjects/Models-Cadl/Generated/FixedIntEnum.Serialization.cs:12]: We've decided to not delete the serialization class for fixed int enum. However, we will not need serialization method here, and replace it with type cast, e.g. `WriteNumber((int)some_enum)`;
