### PR TITLE
fix(common): fixed long int enum is not generated correctly

### LINKED ISSUE #2895: Int enum bug in generated serialization code
In `OperationalInsightsClusterSku.Serialization.cs`, the following generated code cannot compile:
``` C#
if (Optional.IsDefined(Capacity))
{
    writer.WritePropertyName("capacity");
    writer.WriteStringValue(Capacity.Value.ToSerialInt64());
}
```

It should be `writer.WriteNumberValue(Capacity.Value.ToSerialInt64());`.

Original swagger: https://github.com/Azure/azure-rest-api-specs/blob/7d5d1db0c45d6fe0934c97b6a6f9bb34112d42d1/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/stable/2021-06-01/Clusters.json#L528-L540

### PR DESCRIPTION
**Pull request by archerzz**
- add support for long type enum value
- add test case

fix #2895

# Description
<i>Add your description here!</i>

# Checklist

To ensure a quick review and merge, please ensure:
- [ ] The PR has a understandable title and description explaining the _why_ and _what_.
- [ ] The PR is opened in draft if not ready for review yet.
   - If opened in draft, please allocate sufficient time (24 hours) after moving out of draft for review
- [ ] The branch is recent enough to not have merge conflicts upon creation.

# Ready to Land?
- [ ] Build is completely green
   - Submissions with test failures require tracking issue and approval of a CODEOWNER
- [ ] At least one +1 review by a CODEOWNER
- [ ] All -1 reviews are confirmed resolved by the reviewer 
   - Override/Marking reviews stale must be discussed with CODEOWNERS first

### CODE REVIEW

File: test/TestProjects/MgmtExpandResourceTypes/Generated/Models/MemoryType.cs [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+{
+    /// <summary> The MemoryType. </summary>
+    public enum MemoryType
+    {
+        /// <summary> -1. </summary>
+        _1 = -1,
+        /// <summary> 2. </summary>
+        Two = 2,
+        /// <summary> 4. </summary>
+        Four = 4
```
Comment (fengzhou-msft) [inline test/TestProjects/MgmtExpandResourceTypes/Generated/Models/MemoryType.cs:18]: Assigning the long value to enum int may cause out of range issue when the value is very big.

Comment (archerzz) [reply test/TestProjects/MgmtExpandResourceTypes/Generated/Models/MemoryType.cs:18]: correct. we should declare the enum as long, e.g. `public enum MemoryType : long`.

**Review by fengzhou-msft — APPROVED** [review]
