### PR TITLE
fix(generator): enum docs doesn't follow value type

### LINKED ISSUE #5069: ModelWriter.WriteExtensibleEnum can generate incorrectly-typed documentation
See the following generator source:

https://github.com/Azure/autorest.csharp/blob/5088d5b4a3684d0b3f57e536366d8f20c86183e8/src/AutoRest.CSharp/Common/Generation/Writers/ModelWriter.cs#L432-L433

Note that even when `enumType.ValueType` is not `string`, the generated documentation still refers to a `string`. In the (rare) cases where it isn't a string, it should refer to the actual type (ideally, wrapped in a `see cref` tag.)

### PR DESCRIPTION
**Pull request by archerzz**
# Description

- fix hard-coded `string` in the docs of enum implicit conversion method
- refactor codes

fix #5069

# Checklist

To ensure a quick review and merge, please ensure:
- [ ] The PR has a understandable title and description explaining the _why_ and _what_.
- [ ] The PR is opened in draft if not ready for review yet.
   - If opened in draft, please allocate sufficient time (24 hours) after moving out of draft for review
- [ ] The branch is recent enough to not have merge conflicts upon creation.

# Ready to Land?
- [ ] Build is completely green
   - Submissions with test failures require tracking issue and approval of a CODEOWNER
- [ ] At least one +1 review by a CODEOWNER
- [ ] All -1 reviews are confirmed resolved by the reviewer 
   - Override/Marking reviews stale must be discussed with CODEOWNERS first

### CODE REVIEW

File: test/CadlRanchProjects/type/property/value-types/src/Generated/Models/FloatLiteralPropertyProperty.cs [hunk 1]
```diff
@@ -33,7 +33,7 @@ public FloatLiteralPropertyProperty(float value)
         public static bool operator ==(FloatLiteralPropertyProperty left, FloatLiteralPropertyProperty right) => left.Equals(right);
         /// <summary> Determines if two <see cref="FloatLiteralPropertyProperty"/> values are not the same. </summary>
         public static bool operator !=(FloatLiteralPropertyProperty left, FloatLiteralPropertyProperty right) => !left.Equals(right);
-        /// <summary> Converts a string to a <see cref="FloatLiteralPropertyProperty"/>. </summary>
+        /// <summary> Converts a <see cref="float"/> to a <see cref="FloatLiteralPropertyProperty"/>. </summary>
```
Comment (archerzz) [inline test/CadlRanchProjects/type/property/value-types/src/Generated/Models/FloatLiteralPropertyProperty.cs:36]: `float` enum value type

File: test/CadlRanchProjects/type/property/optionality/src/Generated/Models/IntLiteralPropertyProperty.cs [hunk 2]
```diff
@@ -33,7 +33,7 @@ public IntLiteralPropertyProperty(int value)
         public static bool operator ==(IntLiteralPropertyProperty left, IntLiteralPropertyProperty right) => left.Equals(right);
         /// <summary> Determines if two <see cref="IntLiteralPropertyProperty"/> values are not the same. </summary>
         public static bool operator !=(IntLiteralPropertyProperty left, IntLiteralPropertyProperty right) => !left.Equals(right);
-        /// <summary> Converts a string to a <see cref="IntLiteralPropertyProperty"/>. </summary>
+        /// <summary> Converts a <see cref="int"/> to a <see cref="IntLiteralPropertyProperty"/>. </summary>
```
Comment (archerzz) [inline test/CadlRanchProjects/type/property/optionality/src/Generated/Models/IntLiteralPropertyProperty.cs:36]: `int` enum value type

**Comment by archerzz** [comment]
Regen preview: https://github.com/Azure/azure-sdk-for-net/pull/46230

**Review by ArcturusZhang — APPROVED** [review]
